spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 1
    show-sql: false

  datasource:
    url: jdbc:postgresql://nas.local:5433/stocks
    username: postgres
    password: ${DB_POSTGRES_PASSWORD}

